rick: https://www.youtube.com/watch?v=dQw4w9WgXcQ
python: https://www.youtube.com/watch?v=dQw4w9WgXcQ
font: https://www.youtube.com/watch?v=dQw4w9WgXcQ
slogan-generator/?q=cucumber+recovery+group: https://www.youtube.com/watch?v=dQw4w9WgXcQ
