rick: https://www.youtube.com/watch?v=dQw4w9WgXcQ
python: https://www.youtube.com/watch?v=dQw4w9WgXcQ
font: https://www.youtube.com/watch?v=dQw4w9WgXcQ
slogan-generator: https://www.youtube.com/watch?v=dQw4w9WgXcQ
delta-utbud: https://www.youtube.com/watch?v=dQw4w9WgXcQ
alist: https://www.focalors.ltd/
music: https://music.focalors.ltd/
